# This workflow triggers after cargo vet has run.
# It adds a comment to the PR with the results of the cargo vet run.

name: Cargo vet PR comment

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [cargo-vet]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  post-comment-failure:
    # This job runs when the cargo-vet job fails
    # It will download the artifact from the failed job and post a comment on the PR
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: pr
          path: pr/
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: 'Get PR number'
        run: echo "PR_NUMBER=$(cat ./pr/NR)" >> "$GITHUB_ENV"
      
      - name: 'Find existing comment'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: '[cargo vet]'

      - name: 'Comment on PR - Failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            # [cargo vet] Audit Failed

            `cargo vet` has failed in this PR. Please run `cargo vet --locked` locally to check for new or updated unvetted dependencies.
            Details about the vetting process can be found in [README.md](../blob/main/supply-chain/README.md)
                      
            ## If the unvetted dependencies are not needed
            Please modify Cargo.toml file to avoid including the dependencies.
                      
            ## If the unvetted dependencies are needed
            Post a new comment to the PR with your reasoning to help the auditors vet the dependencies.
            After the auditors have vetted the dependencies, the PR will need to be rebased to pick up the new audits and pass this check.
                      
            ### Copy and paste the questionnaire below and provide your answers:
                
            **1. What crates (with version) need to be audited?**
                
            **2. How many of the crates are version updates vs new dependencies?**
                
            **3. Did you confirm none of the already existing crates serve the same purpose?**
                
            **4. Any extra notes to the auditors to help with their audits.**
          edit-mode: replace
  
  post-comment-success:
    # This job runs when the cargo-vet job succeeds after having failed at least once
    # It will update the comment on the PR with a success message
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:      
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: pr
          path: pr/
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: 'Get PR number'
        run: echo "PR_NUMBER=$(cat ./pr/NR)" >> "$GITHUB_ENV"
      
      - name: 'Find existing comment'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: '[cargo vet]'

      - name: 'Comment on PR - Success'
        if: steps.find-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            # [cargo vet] Audit Passed
            `cargo vet` has passed in this PR. No new unvetted dependencies were found.
          edit-mode: replace